import java.util.Random;

//Creating variables and objects to be used in game
int i, x, y, isGameOver;
Coin coin001;
Enemy enemy001;
Player player001;
ArrayList<WallRect> walls;

void setup() {
    //Setting up the settings
    size(200, 200);
    frameRate(8);
    noCursor();
    generateNewLevel();
    isGameOver = 0;
    x = player001.getX();
    y = player001.getY();
}


//The draw Function - This loop is like the main
//Built in with processing
//It is run however many times frames per second is set to
void draw() {
    //Checks the status of the game
    if (isGameOver == 0) {
        //Gets location of player
        x = player001.getX();
        y = player001.getY();
        //Looks to see if a key is pressed then sees what key
        if (keyPressed) {
            //Normal key presses
            if (key == 'w') {
                if (checkAllCollisions(x, y, 1, 0) != 1) {
                    player001.moveY(-10);
                }
            } else if (key == 'a') {
                if (checkAllCollisions(x, y, 2, 0) != 2) {
                    player001.moveX(-10);
                }
            } else if (key == 's') {
                if (checkAllCollisions(x, y, 3, 0) != 3) {
                    player001.moveY(10);
                }
            } else if (key == 'd') {
                if (checkAllCollisions(x, y, 4, 0) != 4) {
                    player001.moveX(10);
                }
                //Jump key presses
            } else if (key == 'i') {
                if (checkAllCollisions(x, y, 5, 0) != 5) {
                    player001.moveY(-20);
                }
            } else if (key == 'j') {
                if (checkAllCollisions(x, y, 6, 0) != 6) {
                    player001.moveX(-20);
                }
            } else if (key == 'k') {
                if (checkAllCollisions(x, y, 7, 0) != 7) {
                    player001.moveY(20);
                }
            } else if (key == 'l') {
                if (checkAllCollisions(x, y, 8, 0) != 8) {
                    player001.moveX(20);
                }
            }
            //Checking on the coin
            if (!coin001.found && coin001.pickedUp(x, y, 10, 10)) {
                player001.addCoins(1);
                println(player001.getNumOfCoins());
            }
        } 
        //Refreshing the board
        fill(#0000FF);
        refreshBoard();
        //Redrawing the player
        player001.redrawPlayer();
        //This allows the Enemy to move only once every 4 frames (twice a second)
        if (i == 4) {
            enemy001.moveTowardsPlayer(x, y);
            i = 0;
        } else {
            enemy001.redrawEnemy();
        }
        i++;
        isGameOver = checkGameOver(player001, enemy001, coin001);
    } else if (isGameOver == 1) {
        int s = second()+3;
        while (second() != s);
        generateNewLevel();
        println("new level");
        isGameOver = 0;   
    }
}



//The randInt Function - Gets a random int between max and min
//@param min is the smallest number that can be picked
//@param max is the largest number that can be picked
//@return randomNum is an integer between min and max
int randInt(int min, int max) {
    Random rand = new Random();
    int randomNum = rand.nextInt((max - min) + 1) + min;
    return randomNum;
}



//The randInt Function - Gets a random int between max and min on an interval
//Example: The parameters 11,49,10 could give you 10,20,30,40
//The bottom and top number are rounded down and inclusive of both ends
//It rounds down to the nearest number divisible by the interval
//@param min is the bottom number (may be rounded down)
//@param max is the top number (may be rounded down)
//@param interval is the number to skip by
//@return randomNum generated by the algorithm
int randInt(int min, int max, int interval) {
    Random rand = new Random();
    int randomNum = (rand.nextInt((max/interval - min/interval) + 1) + min/interval) * interval;
    return randomNum;
}



//The refreshBoard Function - Redraws the map
void refreshBoard() {
    //Redrawing the background
    fill(#888888);
    rect(0, 0, 200, 200);
    fill(#000000);
    //Redrawing the horizontal lines
    for (int i = 10; i != 200; i+=10) {
        line(i, 0, i, 200);
    }
    //Redrawing the vertical lines
    for (int i = 10; i != 200; i+=10) {
        line(0, i, 200, i);
    }
    //Redrawing the walls
    for (int i = 0; i < walls.size (); i++) {
        walls.get(i).redrawWall();
    }
    //Redrawing the coins
    coin001.redrawCoin();
    fill(#0000FF);
}



//The checkAllCollisions Function - Checks collision with all walls and bounds
//@param x is the current x location of the player
//@param y is the current y location of the player
//@param direction is the way the player is trying to walk
//@param noCollision is the value to return if no collisions are detected
//@return collision is the direction of the collision or the noCollision default
int checkAllCollisions(int x, int y, int direction, int noCollision) {
    int collision = noCollision;
    //Updates the movement values to see whether the step you want to take is ok
    switch(direction) {
        //Normal stepping
    case 1: 
        y -= 9; 
        break;
    case 2: 
        x -= 9;
        break;
    case 3: 
        y += 9;
        break;
    case 4: 
        x += 9;
        break;
        //Jumping
    case 5: 
        y -= 20;
        break;
    case 6: 
        x -= 20;
        break;
    case 7: 
        y += 20;
        break;
    case 8: 
        x += 20;
        break;
    }
    //Loops through the walls to get the collision
    for (int i = 0; i < walls.size (); i++) {
        if (!walls.get(i).checkCollision(x, y, 10, 10)) {
            collision = direction;
        }
    }
    //Checks collision with the boundaries
    if (x < 0) {
        collision = direction;
    } else if (y < 0) {
        collision = direction;
    } else if (x > 190) {
        collision = direction;
    } else if (y > 190) {
        collision = direction;
    }
    return collision;
}

//The checkGameOver Function
int checkGameOver(Player player001, Enemy enemy001, Coin coin001) {
    int isGameOver = 0;
    if (player001.getX() == coin001.getX() && player001.getY() == coin001.getY()) {
        //Game Won
        isGameOver = 1;
        fill(#00FF00);
        rect(0,0,200,200);
        fill(#000000);
        textSize(16);
        textAlign(CENTER);
        text("GAME OVER - YOU WIN", 100, 100);
    } else if (player001.getX() == enemy001.getX() && player001.getY() == enemy001.getY()) {
        //Game Loss
        isGameOver = 2;
        fill(#FF0000);
        rect(0,0,200,200);
        fill(#000000);
        textSize(16);
        textAlign(CENTER);
        text("GAME OVER - YOU LOSE", 100, 100);
    }
    return isGameOver;
}

void generateNewLevel() {
    //Drawing the background
    fill(#888888);
    rect(0, 0, 200, 200);
    //Creates grid lines for debugging and testing
    fill(#000000);
    for (int i = 10; i != 200; i+=10) {
        line(i, 0, i, 200);
    }
    for (int i = 10; i != 200; i+=10) {
        line(0, i, 200, i);
    }
    //ArrayList of WallRect objects
    walls = new ArrayList<WallRect>();
    //Build the horizontal walls
    for (int i = 0; i != 5; i++) {
        walls.add(new WallRect(randInt(0, 190, 10), randInt(0, 190, 10), randInt(10, 190, 10), 10));
    }
    //Build the vertical walls
    for (int i = 0; i != 5; i++) {
        walls.add(new WallRect(randInt(0, 190, 10), randInt(0, 190, 10), 10, randInt(10, 190, 10)));
    }
    //Creating a new Coin Object
    coin001 = new Coin(randInt(0, 190, 10), randInt(0, 190, 10));
    //Drawing the Player
    player001 = new Player(0,0,10,10,0);
    //Creating a new Enemy Object
    enemy001 = new Enemy(100, 100);
    i = 0;
}
